api_tokens:
    hashed: false
    operator_token: "<FOOBAR>"
    data_ingest_token: "<FOOBAR>"

api_url: "https://vtq37192.live.dynatrace.com/api"

# Optional But Recommended
cluster_group: "k8s-poc"

cluster_name: "github-workspaces"

# Optional
containers:
    oneagent:
        registry: "docker.io/dynatrace"
        image_name: "dynatrace-oneagent"
        image_tag: "1.303.70.20241211-194654"
    codemodules:
        registry: "docker.io/dynatrace"
        image_name: "dynatrace-codemodules"
        image_tag: "1.303.70.20241211-194654"
    activegate:
        registry: "docker.io/dynatrace"
        image_name: "dynatrace-activegate"
        image_tag: "1.303.41.20241206-221951"

namespace: "dynatrace"

# Optional
namespace_selector_label: 'dynatrace.com/inject: "true"'

# Optional (Default: false)
# skip_cert_check: false