api_tokens:
    # Determines whether API Tokens are provided in a hashed format or a plain text format
    hashed: false
    # Required
    operator_token: ""
    # Required
    data_ingest_token: ""

# Required
# SaaS Format: 'https://<TenantUUID>.live.dynatrace.com/api'
# Managed Format: 'https://<YourDynatraceServerURL>/e/<your-environment-id>/api'
api_url: ""

# Optional But Recommended
cluster_group: ""

# Required
cluster_name: ""

# Optional
# containers:
#     oneagent:
#         registry: "docker.io/dynatrace"
#         image_name: "dynatrace-oneagent"
#         image_tag: "1.303.70.20241211-194654"
#     codemodules:
#         registry: "docker.io/dynatrace"
#         image_name: "dynatrace-codemodules"
#         image_tag: "1.303.70.20241211-194654"
#     activegate:
#         registry: "docker.io/dynatrace"
#         image_name: "dynatrace-activegate"
#         image_tag: "1.303.41.20241206-221951"

# Optional
# namespace: "dynatrace"

# Optional
# namespace_selector_label: 'dynatrace.com/inject: "true"'

# Optional (Default: false)
# skip_cert_check: false

# Optional
# --> Define OneAgent Resource Constraints
# one_agent:
#   resources:
#     requests:
#       cpu: "100m"
#       memory: "512Mi"
#     limits:
#       cpu: "300m"
#       memory: "1.5Gi"
#   init_resources:
#     requests:
#       cpu: "30m"
#       memory: "30Mi"
#     limits:
#       cpu: "100m"
#       memory: "60Mi"

# Optional
# --> Define ActiveGate Resource Constraints
# activegate:
#   resources:
#     replicas: 1
#     requests:
#       cpu: "500m"
#       memory: "512Mi"
#     limits:
#       cpu: "1000m"
#       memory: "1.5Gi"