apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-app-team-c
  namespace: observability
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-app-team-c
  template:
    metadata:
      labels:
        app: test-app-team-c
    spec:
      nodeSelector:
        kubernetes.io/hostname: kind-worker
      volumes:
        - name: otel-config
          configMap:
            name: otel-collector-config
      containers:
        - name: otel-collector
          image: ghcr.io/dynatrace/dynatrace-otel-collector/dynatrace-otel-collector:0.44.0
          args: ["--config", "/conf/otel-collector-config.yaml"]
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          volumeMounts:
            - name: otel-config
              mountPath: /conf
          env:
            - name: DT_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: otel-auth-secret-team-c
                  key: DT_API_TOKEN
            - name: DT_ENDPOINT
              value: "https://tvw24978.live.dynatrace.com/api/v2/otlp"
            - name: DT_COSTCENTER
              value: "teamC"
            - name: DT_PRODUCT
              value: "biz"
            - name: DT_SECURITY_CONTEXT
              value: "teamC"
        - name: app-container
          image: test-image:0.1
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          env:
            - name: OTLP_METRICS_URL
              value: "http://localhost:4318/v1/metrics"
            - name: OTLP_LOGS_URL
              value: "http://localhost:4318/v1/logs"
            - name: DT_COSTCENTER
              value: "teamC"
            - name: DT_PRODUCT
              value: "biz"