---

apiVersion: v1
kind: Secret
metadata:
  name: otel-auth-secret-team-a
  namespace: observability
stringData:
  DT_API_TOKEN: "<TOKEN>"

---

apiVersion: v1
kind: Secret
metadata:
  name: otel-auth-secret-team-b
  namespace: observability
stringData:
  DT_API_TOKEN: "<TOKEN>"

---

apiVersion: v1
kind: Secret
metadata:
  name: otel-auth-secret-team-c
  namespace: observability
stringData:
  DT_API_TOKEN: "<TOKEN>"