apiVersion: v1
kind: Namespace
metadata:
  name: easytravel-web
---
apiVersion: v1
kind: Namespace
metadata:
  name: easytravel-business
---
apiVersion: v1
kind: Namespace
metadata:
  name: easytravel-backend